### ISSUE TITLE
TV turns on even when not connected to computer.

### ISSUE THREAD

**Issue by hamzaahmadk** [cmer/lg-tv-control-macos#10]
I am using my C2 as a monitor for my MacBook. When I'm using my MacBook without connecting it to the TV, the display turns on which then has to be manually turned off. Does anyone have any idea on how to fix this?

**Comment by zakkhoyt** [comment]
Hey @hamzaahmadk. I was encountering this bug too. 

There is no check to see if the TV is connected to the computer before issuing the "on" command. I added a fix for that in this [pull request](https://github.com/cmer/lg-tv-control-macos/pull/9) if you want to try it out.
