### ISSUE TITLE
Getting an error upon running "lgtv scan ssl"

### ISSUE THREAD

**Issue by LouieMjr** [cmer/lg-tv-control-macos#12]
Traceback (most recent call last):
  File "/Users/lmenx/opt/lgtv/bin/lgtv", line 33, in <module>
    sys.exit(load_entry_point('LGTV==0.3', 'console_scripts', 'lgtv')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lmenx/opt/lgtv/lib/python3.11/site-packages/LGTV/__init__.py", line 150, in main
    ws.connect()
  File "/Users/lmenx/opt/lgtv/lib/python3.11/site-packages/ws4py/client/__init__.py", line 224, in connect
    bytes = self.sock.recv(128)
            ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1263, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1136, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SSL: TLSV13_ALERT_CERTIFICATE_REQUIRED] tlsv13 alert certificate required (_ssl.c:2576)

Not sure what to do from here

**Comment by devantler** [comment]
Did you run the commands as instructed in the README prior to this? 🙂 Do running these commands fail as well?

**Comment by LouieMjr** [comment]
lgtv scan ssl
Unknown device
b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nDATE: Thu, 01 Jun 2023 18:42:00 GMT\r\nEXT:\r\nLOCATION: http://192.168.4.1:1900/igd.xml\r\nSERVER: eeroOS/latest UPnP/1.0 eero/latest\r\nST: upnp:rootdevice\r\nUSN: uuid:fcdb9233-a63f-41da-b42c-7cfeb99c8adf::upnp:rootdevice\r\n\r\n' ('192.168.4.1', 1900)
Unknown device
b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nDATE: Thu, 01 Jun 2023 18:42:00 GMT\r\nEXT:\r\nLOCATION: http://192.168.4.1:1900/igd.xml\r\nSERVER: eeroOS/latest UPnP/1.0 eero/latest\r\nST: uuid:fcdb9233-a63f-41da-b42c-7cfeb99c8adf\r\nUSN: uuid:fcdb9233-a63f-41da-b42c-7cfeb99c8adf\r\n\r\n' ('192.168.4.1', 1900)
Unknown device
b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nDATE: Thu, 01 Jun 2023 18:42:00 GMT\r\nEXT:\r\nLOCATION: http://192.168.4.1:1900/igd.xml\r\nSERVER: eeroOS/latest UPnP/1.0 eero/latest\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:fcdb9233-a63f-41da-b42c-7cfeb99c8adf::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n' ('192.168.4.1', 1900)
Unknown device
b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nDATE: Thu, 01 Jun 2023 18:42:00 GMT\r\nEXT:\r\nLOCATION: http://192.168.4.1:1900/igd.xml\r\nSERVER: eeroOS/latest UPnP/1.0 eero/latest\r\nST: urn:schemas-upnp-org:service:Layer3Forwarding:1\r\nUSN: uuid:fcdb9233-a63f-41da-b42c-7cfeb99c8adf::urn:schemas-upnp-org:service:Layer3Forwarding:1\r\n\r\n' ('192.168.4.1', 1900)
{"result": "failed", "count": 0}

**Comment by LouieMjr** [comment]
> Did you run the commands as instructed in the README prior to this? 🙂 Do running these commands fail as well?
> 
> Otherwise it sounds like the host/tv you are trying to connect to requires a client certificate. My tv prompted me to accept the connection the first time i ran the auth command. Maybe you skipped that?

After what point did it prompt you to accept the connection?

**Comment by devantler** [comment]
I got the prompt on the tv when I ran the Auth command. I have an LG C2 for reference.

But I am not sure what is going on here. The error seems unrelated to the script from this repo.

The log from your scan command looks incorrect as well. Maybe your home network setup has something that blocks it from finding your lg tv on the network? Can you ping the LG TV directly?

**Comment by LouieMjr** [comment]
> I got the prompt on the tv when I ran the Auth command. I have an LG C2 for reference.
> 
> But I am not sure what is going on here. The error seems unrelated to the script from this repo.
> 
> The log from your scan command looks incorrect as well. Maybe your home network setup has something that blocks it from finding your lg tv on the network? Can you ping the LG TV directly?

So I entered the correct ip address for the auth part and I got the prompt on my tv afterwards. Im not able to turn the screen off using "lgtv MyTV screenOff ssl". But its not turning off or on when putting/waking from sleep.

I set the debug variable to true and in the hammerspoon console, its telling me theres no tv connected. Im using a LGC2 as well btw. I'm seeing this when I reload the config...

2023-06-02 20:15:31: -- Lazy extension loading enabled
2023-06-02 20:15:31: -- Loading ~/.hammerspoon/init.lua
2023-06-02 20:15:31: TV name: MyTV
2023-06-02 20:15:31: TV input: HDMI_1
2023-06-02 20:15:31: LGTV path: ~/opt/lgtv/bin/lgtv
2023-06-02 20:15:31: LGTV command: ~/opt/lgtv/bin/lgtv MyTV
2023-06-02 20:15:31: SSL: true
2023-06-02 20:15:31: App ID: com.webos.app.hdmi1
2023-06-02 20:15:31: lgtv_disabled: false
2023-06-02 20:15:31: Executing command: ~/opt/lgtv/bin/lgtv MyTV swInfo ssl
2023-06-02 20:15:32: {"type": "response", "id": "sw_info_0", "payload": {"returnValue": true, "product_name": "webOSTV 7.0", "model_name": "HE_DTV_W22O_AFABATAA", "sw_type": "FIRMWARE", "major_ver": "03", "minor_ver": "33.16", "country": "US2", "country_group": "US", "device_id": "7c:64:6c:46:0d:1f", "auth_flag": "N", "ignore_disable": "N", "eco_info": "01", "config_key": "00", "language_code": "en-US"}}
{"closing": {"code": 1000, "reason": ""}}

2023-06-02 20:15:32: Executing command: ~/opt/lgtv/bin/lgtv MyTV getForegroundAppInfo ssl
2023-06-02 20:15:32: {"type": "response", "id": "0", "payload": {"returnValue": true, "appId": "com.webos.app.hdmi1", "processId": "", "windowId": ""}}
{"closing": {"code": 1000, "reason": ""}}

2023-06-02 20:15:32: -- Loading extension: screen
2023-06-02 20:15:32: Connected screens: { [1] = hs.screen: LG C2 (0x600001f4e2f8),} 
2023-06-02 20:15:32: No screens are connected
2023-06-02 20:15:32: TV is connected? false
2023-06-02 20:15:32: -- Loading extension: caffeinate
2023-06-02 20:15:32: -- Done.

**Comment by devantler** [comment]
Sounds like you almost got it working now. That is great news!

Have you double checked that the HDMI port and tv name is correct kn the script?

The tv name must match with what you choose to call it when you ran the auth command.

The HDMI port must match with the port that you use on the TV. It uses this port to determine if there is a connected tv, so my guess is this is your issue :-)

**Comment by devantler** [comment]
In this log it shows you what TV's you have connected:

`2023-06-02 20:15:32: Connected screens: { [1] = hs.screen: LG C2 (0x600001f4e2f8),}`

The name `LG C2` must be in the identifiers in the script for this to work. Try changing the following in `lgtv_init.lua`:

`local connected_tv_identifiers = {"LG TV", "LG TV SSCR2"} -- Used to identify the TV when it's connected to this computer`

To:

`local connected_tv_identifiers = {"LG C2"} -- Used to identify the TV when it's connected to this computer`

**Comment by LouieMjr** [comment]
> In this log it shows you what TV's you have connected:
> 
> `2023-06-02 20:15:32: Connected screens: { [1] = hs.screen: LG C2 (0x600001f4e2f8),}`
> 
> The name `LG C2` must be in the identifiers in the script for this to work. Try changing the following in `lgtv_init.lua`:
> 
> `local connected_tv_identifiers = {"LG TV", "LG TV SSCR2"} -- Used to identify the TV when it's connected to this computer`
> 
> To:
> 
> `local connected_tv_identifiers = {"LG C2"} -- Used to identify the TV when it's connected to this computer`
> 
> Did you, by chance, change the settings on the TV that might have changed this name? Otherwise, we might want to add this tv identifier as a default :-)

Ah this was it! I did change the name of the TV when i first got it. I looked at that line and thought maybe I just should change it to "LG C2" but wasn't sure if I should mess with anything so I didn't. Should've just played around and tried.

As for the tv_input. I should keep it as "HDMI_1", since thats the port Im connected to? I changed the name of the input to "Mac" on the TV but its still the HDMI 1 port that Im plugged into. Its turning on and off with it as "HDMI_1", so I'd assume keep it as that. 

I appreciate your help!
