### ISSUE TITLE
Display will turn on when another HDMI port is selected

### ISSUE THREAD

**Issue by Shasoosh** [cmer/lg-tv-control-macos#14]
My C2 TV is connected to my PC and Mac.
HDMI 1 - PC
HDMI 2 - Mac

The issue happens when my mac is connected to the TV but another HDMI is selected (HDMI 1). When my mac wakes up it will trigger the tv to turn ON regardless of the HDMI that is selected.

Steps to reproduce:
1. TV is connected to HDMI 1 - PC
2. PC and display are turned OFF
3. Mac will randomly (or manually) wake up and will turn on the TV to NO_SIGNAL
4. TV Will stay on **until I manually turn it off** because HDMI 1 is selected and `prevent_sleep_when_using_other_input = true `

I guess the best solution for this would be something like `prevent_wake_when_using_other_input = true`  but I don't know if that's possible.

* This is not the same issue as https://github.com/cmer/lg-tv-control-macos/issues/10 as the tv is connected to the mac but the HDMI is not selected.

* Due to corporate policy I can't set "Enable Power Nap" and "Wake for network access" to "Never".

Thanks.

**Comment by cmer** [comment]
Are you saying that you'd like the script to detect which input the TV is on, and not wake it if it's not HDMI 2?
