### ISSUE TITLE
lgtv scan not working

### ISSUE THREAD

**Issue by cdam06** [cmer/lg-tv-control-macos#19]
I don't have previous coding experience but I was able to successfully follow all of the installation steps. I am running into a problem when use the `lgtv scan ssl` command. Any help would be appreciated.

This is what I'm seeing:
(lgtv) chandu@ChandusacStudio lgtv % lgtv scan ssl
Traceback (most recent call last):
  File "/Users/chandu/opt/lgtv/bin/lgtv", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/chandu/opt/lgtv/lib/python3.11/site-packages/LGTV/__init__.py", line 123, in main
    results = LGTVScan()
              ^^^^^^^^^^
  File "/Users/chandu/opt/lgtv/lib/python3.11/site-packages/LGTV/scan.py", line 25, in LGTVScan
    response, address = sock.recvfrom(512)
                        ^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

**Comment by sanioka** [comment]
Workaround: 

Do not wait `lgtv scan ssl` at all.

You can manually find IP address inside LG TV menu / WiFi / Advanced, and go to next step.

`lgtv auth <ip_address_here> MyTV ssl`

**Comment by moontails** [comment]
I skipped scan and my screen didn't turn off, so wondering what I am missing.... 
can we add expected out put to the subsequent commands after auth?

**Comment by Krizid** [comment]
try this command
lgtv --ssl auth <ip_address_here> MyTV

**Comment by cmer** [comment]
I just updated the script to work with the latest version of LGWebOSRemote. Reinstall everything by following the new instructions in README.md. It should solve your problem.
