### ISSUE TITLE
Does this function via a dock connector?

### ISSUE THREAD

**Issue by murdoc1313** [cmer/lg-tv-control-macos#25]
I followed the instructions and im able to control the TV via terminal, I tried a number of inputs provided in the remote commands. 
However auto wake does not seem to work. 

I dont know if this is a hammer spoon issue, only script change input is HDMI 3 as im able to control the TV via terminal.
<local tv_input = "HDMI_3" -- Input to which your Mac is connected>
or 
is this Because im using a dock as I have multiple displays running from the M1 Pro? I know I could test this easily, but wires are tucked away, maybe someone already knows the answer to this?

**Comment by murdoc1313** [comment]
Soz - it was something as simple as accessibility setting for hammer spoon not being approved. 

It WORKS via external dock as well.

**Comment by NissarAK84** [comment]
I am having the same issue here, I don't know what is wrong.

**Comment by cmer** [comment]
Enable debugging in the script and see what the Hammerspoon logs say. Should be easy to figure out what's wrong that way.
