### ISSUE TITLE
no pairing message being send to TV to further add it

### ISSUE THREAD

**Issue by Amarettooo** [cmer/lg-tv-control-macos#27]
Hello. He indicated my IP address, I enter it and nothing happens. There is no confirmation on the TV and nothing works :(
Lg c2 42, webos 7.3.1-43 (mullet-mebbin).

![image](https://github.com/cmer/lg-tv-control-macos/assets/151795691/d6c3a6ae-0d46-4742-941f-1a83da56c9f2)

**Comment by Amarettooo** [comment]
> try lgtv --ssl auth yourip MyTV

hello. Thanks, but I'm getting an error

![image](https://github.com/cmer/lg-tv-control-macos/assets/151795691/a894b1e6-2996-493f-97c2-1aef1d5fa4b7)

**Comment by BawlerPepsi** [comment]
> try lgtv --ssl auth yourip MyTV

this worked for me, until the next step. the tv doesn't turn off. is it related to the fact that i only have "[lg] webos tv oled42c2..." appearing in my terminal when i scan?

_**MacBookPro ~ % mkdir -p ~/opt**_
python -m venv ~/opt/lgtv
cd ~/opt/lgtv
source bin/activate
pip install git+https://github.com/klattimer/LGWebOSRemote
Collecting git+https://github.com/klattimer/LGWebOSRemote
  Cloning https://github.com/klattimer/LGWebOSRemote to /private/var/folders/9l/_7wzz91d2wxgd23x6btvyrd80000gn/T/pip-req-build-kw4asud7
  Running command git clone --filter=blob:none --quiet https://github.com/klattimer/LGWebOSRemote /private/var/folders/9l/_7wzz91d2wxgd23x6btvyrd80000gn/T/pip-req-build-kw4asud7
  Resolved https://github.com/klattimer/LGWebOSRemote to commit 63e0e503a1808506725107a8ac3d02e87cc84734
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: wakeonlan in ./lib/python3.9/site-packages (from LGTV==0.3) (3.1.0)
Requirement already satisfied: ws4py in ./lib/python3.9/site-packages (from LGTV==0.3) (0.5.1)
Requirement already satisfied: requests in ./lib/python3.9/site-packages (from LGTV==0.3) (2.31.0)
Requirement already satisfied: getmac in ./lib/python3.9/site-packages (from LGTV==0.3) (0.9.4)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.9/site-packages (from requests->LGTV==0.3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.9/site-packages (from requests->LGTV==0.3) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib/python3.9/site-packages (from requests->LGTV==0.3) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.9/site-packages (from requests->LGTV==0.3) (2023.11.17)

**_(lgtv)  lgtv % lgtv scan ssl_**
/Users//opt/lgtv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{"result": "ok", "count": 1, "list": [{"uuid": "1345987b-3a10-e8dc-b5c7-d0999b993084", "tv_name": "[LG] webOS TV OLED42C2KNB", "address": "192.168.1.12"}]}
(lgtv)  lgtv % 



_**(lgtv)  lgtv % lgtv --ssl auth 192.168.1.12 mytv**_

/Users//opt/lgtv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

DEBUG:getmac:Initializing 'ip4' method cache (platform: 'darwin')
DEBUG:getmac:Finished initializing 'ip4' method cache
DEBUG:getmac:Raw MAC found: 4c:22:f3:7a:cd:be

Please accept the pairing request on your LG TV

DEBUG:ws4py:Closing message received (1000) 'b'''
{"closing": {"code": 1000, "reason": ""}}
Wrote config file: /Users//.lgtv/config.json
(lgtv)  lgtv %

**Comment by cmer** [comment]
I just updated the script to work with the latest version of LGWebOSRemote. Reinstall everything by following the new instructions in README.md. It should solve your problem.
