### ISSUE TITLE
urllib3 v2 only supports OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by Bobby4Life** [cmer/lg-tv-control-macos#28]
Hello, 

firstly thanks for the great workaround! Unfortunately I have the issue with a not supported SSL version: 

(lgtv) bob@Mac-mini-from-bob lgtv % lgtv scan ssl
/Users/bob/opt/lgtv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{"result": "ok", "count": 1, "list": [{"uuid": "e9d0203a-f42d-f75e-2df0-67fdfacb7f34", "tv_name": "Monitor", "address": "192.168.178.70"}]} 

As to be seen the issue seems to be solved but I have to confess I'm kinda overstrained with it. Can somebody help me out?

**Comment by cmer** [comment]
This is a Python issue, not directly related to this repo. You need to make sure you compile Python packages with OpenSSL and not LibreSSL it seems. Not sure what your setup currently looks like so it's hard for me to help you with it.
