### ISSUE TITLE
Not waking from sleep

### ISSUE THREAD

**Issue by syncr** [cmer/lg-tv-control-macos#29]
Mac Mini M2 running Ventura 13.5.1
I've previously had everything working fine but some months ago my LG C2 would no longer wake from sleep without using the remote control. Display sleeps fine from terminal, menu command, or hot corner.

This morning I made sure Hammerspoon and LGWebOSRemote were on their latest versions and I re-authenticated with `lgtv auth` and validated with the `screenOff` function. However the problem continues exactly as described above. What I did notice today in testing was that the display will sometimes wake to mouse/keyboard prompt immediately after being put to sleep, but even this is inconsistent. 

It's possible that I don't have a correct power setting elsewhere I suppose. I vaguely remember months ago making a change because the monitor wasn't sleeping after being idle for some time (or maybe the Mac was sleeping, but the display stayed active. Don't remember).  I've poked around in the LG settings and enabled Quick Start+ but the changes I've made haven't produced a fix. 

Appreciate any help someone can provide.

**Comment by cmer** [comment]
Enable debugging in the script and see what the Hammerspoon logs say. It'll be easier to figure out what's wrong that way.
