### ISSUE TITLE
Issue with Hammerscript

### ISSUE THREAD

**Issue by Eriksrevenge1** [cmer/lg-tv-control-macos#34]
So I've done everything, and I'm getting this error in the Hammerspoon Console

"*** ERROR: /Users/(**myname)**/.hammerspoon/init.lua:180: attempt to index a nil value (global 'tap')
stack traceback:
	/Users/**(myname)**/.hammerspoon/init.lua:180: in main chunk
	[C]: in function 'xpcall'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:723: in function 'hs._coresetup.setup'
	(...tail calls...)"

**Comment by cmer** [comment]
I completely messed up a couple of days ago. It's been resolved.
