### ISSUE TITLE
LG C3 

### ISSUE THREAD

**Issue by ctkidd78** [cmer/lg-tv-control-macos#38]
Does any of this work with the latest versions of the LG C3. I can't get none of the code to work in terminal. When inputting the auth mytv it gives an ssl error and I guess never authorizes the connection and if I manage to get past that I can't send any commands to the TV giving me the help menu every time. Thanks

**Comment by Aurshur** [comment]
I have an LG C3 and it is working fine for me on the latest firmware.

You will encounter a bug with ws4py and [the workaround is to roll back to Python 3.11](https://github.com/klattimer/LGWebOSRemote/issues/140). After that you should have no issues authenticating your TV.

**Comment by cmer** [comment]
I have added an installation script to work around the different issues with newer Python versions. Please reinstall with the installation script. It might solve your issue.
