### ISSUE TITLE
Having trouble getting this to work

### ISSUE THREAD

**Issue by uxmilos** [cmer/lg-tv-control-macos#4]
This is the error I get, any help appreciated

`2023-03-30 09:28:35: -- Lazy extension loading enabled
2023-03-30 09:28:35: -- Loading ~/.hammerspoon/init.lua
2023-03-30 09:28:35: *** ERROR: error loading module 'lgtv' from file '/Users/milos/.hammerspoon/lgtv.lua':
	/Users/milos/.hammerspoon/lgtv.lua:10: syntax error near 'local'
stack traceback:
	[C]: in ?
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	/Users/milos/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:723: in function 'hs._coresetup.setup'
	(...tail calls...)`

**Comment by cmer** [comment]
Make sure you use the latest version.
