### ISSUE TITLE
Macbook enters clamshell mode when lid closed with no keyboard and mouse (LG C3 but I think it happens on all)

### ISSUE THREAD

**Issue by slawek-wozniak** [cmer/lg-tv-control-macos#42]
When I close my macbook lid it seems to enter clamshell mode instead of going to sleep...
I have no external keyboard and mouse plugged into the device, so I find it frustrating when I close the lid it seems to enter clamshell mode instead of sleeping. And the TV stays on.

Is there any way to modify this?

**Comment by cmer** [comment]
This is not an issue with this script. Closing.
