### ISSUE TITLE
Is all this tinkering effectively useless? (LG Always ready)

### ISSUE THREAD

**Issue by slawek-wozniak** [cmer/lg-tv-control-macos#43]
https://www.lg.com/us/support/help-library/lg-tv-how-to-use-the-alway-ready-feature-webos-22-CT10000018-20153280995321

I don't understand how no one online mentioned this. Everyone says that having to use the remote to turn it on is a major issue of using an LG tv as a monitor... But there's a setting called Always Ready where it will automatically wake up when you open your laptop lid or sit it down on the table and plug in the HDMI.

It also works seemingly twice as fast as this hammerspoon method cause it's not sending something over the internet.

Are you aware of this feature? Is there a reason you don't use it? Does it drain considerably more power than a regular monitor going into standby mode when you turn off the pc? Fundamentally there's something powered up in both a monitor and this tv to be able to respond to pc activity. I probably don't understand how the monitor sleep cycle works but I know on my old gaming monitor the power brick still had a green LED on it even when it was sleeping.

**Comment by EthycalOne** [comment]
I'm sure you've discovered by now that the LG always ready feature does not
make the LG turn off and on like a monitor. It's used to display wallpaper
and screensavers, ensure that bluetooth remains connected to play music
through, and voice assistant remains on after you've powered the TV off.

**Comment by slawek-wozniak** [comment]
Incorrect, you can turn off the wallpaper entirely, and even turn off the standby light, meaning when it loses signal from your laptop it turns the pixels off, and waits to be turned on again.
I'll be going to sleep soon and I'll test if it works in the morning but I did a preliminary test and it worked.

Perhaps this is only on my one then? C3? Or were you not aware you can turn off the wallpapers.

**Comment by slawek-wozniak** [comment]
Oh, my bad, It appears hammerspoon was running even though I thought I quit it. 
So it appeared to wake up while in always ready mode, but it was the lua script waking it up, oopsie.
😮‍💨😮‍💨😮‍💨

**Comment by EthycalOne** [comment]
Last time I checked, yes, you could turn off the wallpaper but a clock or lg overlay remained on. It was some time ago, perhaps they fixed that. Check it out, let us knowOn Jan 10, 2024, at 18:35, Slawek Wozniak ***@***.***> wrote:﻿
Incorrect, you can turn off the wallpaper entirely, and even turn off the standby light, meaning when it loses signal from your laptop it turns the pixels off, and waits to be turned on again.
I'll be going to sleep soon and I'll test if it works in the morning but I did a preliminary test and it worked.
Perhaps this is only on my one then? C3? Or were you not aware you can turn off the wallpapers.

**Comment by EthycalOne** [comment]
No big deal, now we know.On Jan 10, 2024, at 18:40, Slawek Wozniak ***@***.***> wrote:﻿
Oh, my bad, It appears hammerspoon was running even though I thought I quit it.
So it appeared to wake up while in always ready mode, but it was the lua script waking it up, oopsie.
😮‍💨😮‍💨😮‍💨
