### ISSUE TITLE
Readme setup guide PIPX error

### ISSUE THREAD

**Issue by slawek-wozniak** [cmer/lg-tv-control-macos#44]
I spent roughly two hours trying to figure out why I couldn't get this to work, in my case what happened is:

the setup guide tells you to:
* install pipx
* install LGTV package with pipx, but this automatically installed it with an enviroment of 3.12.x 

So I had the SSL error where I can't send the request to the tv because:

```
~ % lgtv auth <ip> MyTV --ssl
Traceback (most recent call last):
  File "/Users/user/.local/bin/lgtv", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/Library/Application Support/pipx/venvs/lgtv/lib/python3.12/site-packages/LGTV/__init__.py", line 137, in main
    ws.connect()
  File "/Users/user/Library/Application Support/pipx/venvs/lgtv/lib/python3.12/site-packages/ws4py/client/__init__.py", line 214, in connect
    self.sock = ssl.wrap_socket(self.sock, **self.ssl_options)
                ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

Chatgpt4 figured it out for me but it took a while. I ended up having to uninstall the lgtv package and unisntall pipx and install a tool that lets me switch between different pythons and I think I installed python three seperate times in total?

Btw please don't ready any of this in a negative tone, I had fun tinkering with making the tv a bit comfier to use as a monitor.

**Comment by aximcore** [comment]
Pipx is using a Python 3.12 version that is not compatible with the LGWebOSRemote package. To fix this, you need to remove the current package and then reinstall it with a Python 3.11 version. You can do this using the following commands:

```
pipx uninstall lgtv
pipx install git+https://github.com/klattimer/LGWebOSRemote.git --python python3.11
```

**Comment by cmer** [comment]
I have added an installation script to work around the different issues with newer Python versions. Please reinstall with the installation script. It might solve your issue.
