### ISSUE TITLE
Hammerspoon not responding in macOS Sonoma 14.2.1

### ISSUE THREAD

**Issue by Aurshur** [cmer/lg-tv-control-macos#45]
With the latest system update, Hammerspoon now hangs when it tries to initiate the script. It does not produce any error logs, but just simply stops responding. Restarting and re-installing the program has no effect.

**Comment by Shasoosh** [comment]
I'm getting this too on Ventura 13.6.3. Hammerspoon will hang when lgtv_init.lua is inside the hammerspoon folder.

**Comment by cmer-sh** [comment]
I have added an installation script to work around the different issues with newer Python versions. Please reinstall with the installation script. It might solve your issue.
