### ISSUE TITLE
Mute button erroring in Hammerspoon due to typo in script

### ISSUE THREAD

**Issue by ssft** [cmer/lg-tv-control-macos#46]
I noticed when attempting to mute it was producing an error in the hs console "attempt to call a nil value (global 'exec_command')". I changed the exec_command on line 165 to lgtv_exec_command to get it working:

local audio_status = hs.json.decode(exec_command("audioStatus"):gmatch('%b{}')())

Should be:

local audio_status = hs.json.decode(lgtv_exec_command("audioStatus"):gmatch('%b{}')())

**Comment by cmer** [comment]
Fixed. Thanks!
