### ISSUE TITLE
Terminal freezing after authentication - Hammerspoon freezing at launch macOS Sonoma 14.2.1

### ISSUE THREAD

**Issue by Aurshur** [cmer/lg-tv-control-macos#48]
After uninstalling and reinstalling with the new script I am now unable to get any commands to work after authentication.

I can register my LG C3 no issues, but attempting to run any command be it swinfo or screen off causes terminal to hang and likewise Hammerspoon hangs as soon as it tries to run the script. My C3 is running 03.30.70 which is the current firmware.

**Comment by rshejnberg** [comment]
Seeing the same behavior on my C2

**Comment by cmer** [comment]
Did you try debugging the scripts to see where it hangs?
