### ISSUE TITLE
Feature / Help request

### ISSUE THREAD

**Issue by elpocholo7** [cmer/lg-tv-control-macos#49]
Hi Carl, first of all I want to thank you for this amazing automated script that you've created, it changes the way I can use my Mac on my workstation setup. 
I didn't know how to contact you directly because this is not really an issue but I wanted to ask you if you could help me implementing an additional command when the script wakes the TV up so that also a binary shell command to reset the VMI7100 adapter that I use is evoked (it always freezes after waking my LG C2, thus requiring a physical / software command reset).
The binary I'm referencing to is included in the app BetterDisplay (https://github.com/waydabber/betterdisplaycli), the command itself is "betterdisplaycli perform -resetVMM7100". Thanks a lot for your work.

**Comment by cmer** [comment]
I have implemented this for you. See `after_wake_command` in the new script! Just add your command in there and it should work.

**Comment by elpocholo7** [comment]
I can only thank you Carl!

Much appreciated !

Kind regards
Oreste

On 6 Dec 2024, at 06:21, Carl Mercier ***@***.***> wrote:

﻿

Closed #49<https://github.com/cmer/lg-tv-control-macos/issues/49> as completed.
