### ISSUE TITLE
LG New IP Control Settings.

### ISSUE THREAD

**Issue by prowlmedia** [cmer/lg-tv-control-macos#51]
Thanks of the method and instructions. Even an idiot like me can follow and make it work! 

So with the latest 13.30.56 update we now have a IP control setting under general.   with SDDP I don't know if that can simplify the method?

**Comment by cmer** [comment]
Interesting I'll take a look!

**Comment by prowlmedia** [comment]
Hi, did you this help out in any way?   I'dd love to take hammer spoon out of the equation it seems to hang a lot.

**Comment by cmer-sh** [comment]
Hammerspoon has never hung for me. Rock solid. 

Hammerspoon is used to watch for system events only.

**Comment by prowlmedia** [comment]
ah ok... I am a squib when it comes to this stuff... I have an overview understanding and can follow instructions but no good at actual coding.   This is the error I am getting.  
"2024-07-25 10:47:34: 10:47:34 ERROR:   LuaSkin: hs.caffeinate.watcher callback: /Users/andy/.hammerspoon/lgtv_init.lua:141: attempt to concatenate a nil value
stack traceback:"

**Comment by cmer** [comment]
Would need to see more logs to be able to help.
