### ISSUE TITLE
LG C2 42” not turning ON after sleep

### ISSUE THREAD

**Issue by beauhaan** [cmer/lg-tv-control-macos#53]
I’m not sure if there’s a setting or conflict that’s happening, but I’ve gone through the whole process and yet when left idle for a couple of hours, the screen will NOT turn itself back on.

For instance, after nudging the mouse to wake the Mac Studio up, the two side monitors will wake up and present the login screen to the left-side monitor. Then a couple of seconds later, the login screen will switch to neither monitors (my guess is that it is now occupying the center LG C2) but there’s nothing on the actual screen.

When I press the LG remote controllers power button, then the LG turns on and displays HDMI 1, and then it’s back to normal.

I mean, I’m okay settling with this minor annoyance, but was wondering what the symptom could be?

I do have BetterDisplay running, which _could_ be the problem right? But I do wonder what setting could be causing this if so.

**Comment by EnglishOstrich** [comment]
I am having a similar issue with an LG C2 42". There are no additional displays, but they are running through a Thunderbolt hub. TV will turn off when the laptop goes to sleep but then will not turn on when the computer is woken back up. The TV turns on with the remote just fine after turning off with a laptop sleep. The laptop is in clamshell mode, using an Apple Bluetooth keyboard and Alfred Commands to sleep.

**Comment by beauhaan** [comment]
what's been working _so far_ has been going into the "Preferences" menu of Hammerspoon and checking the box for "Show Dock Icon"

LG C2 42" has been turning ON and OFF with the other monitors consistently over the last several days, even after 24-hours, it turns ON~

**Comment by prowlmedia** [comment]
> what's been working _so far_ has been going into the "Preferences" menu of Hammerspoon and checking the box for "Show Dock Icon"
> 
> LG C2 42" has been turning ON and OFF with the other monitors consistently over the last several days, even after 24-hours, it turns ON~

Yes.  I concur.  Weird right. 

Works consistently if the dock
Icon is on.  Crashes consistently if its off!   Very odd.  I can't think what is happening there.

**Comment by EnglishOstrich** [comment]
> what's been working _so far_ has been going into the "Preferences" menu of Hammerspoon and checking the box for "Show Dock Icon"
> 
> LG C2 42" has been turning ON and OFF with the other monitors consistently over the last several days, even after 24-hours, it turns ON~

Same here; works consistently if Hammerspoon is set to stay in the dock. Very strange

**Comment by cmer** [comment]
My Hammerspoon is not in the dock and things are working just fine. This is definitely strange.
