### ISSUE TITLE
PC Input mode

### ISSUE THREAD

**Issue by travispamaral** [cmer/lg-tv-control-macos#54]
Hey there! Thanks so much for this library. Most things work as expected but what I keep running into is needing to switch my hdmi input mode to PC after connecting my macbook. I tried using [this library](https://github.com/chros73/bscpylgtv) as used in [this init file](https://github.com/hamzaahmadk/lghdmitype/blob/main/lgtv_init.lua#L8) but the library times out and doesn't seem to work. Is there anyway through this library to change the mode so I don't have to keep opening input settings every day? 🙏🏼

**Comment by tf5bassist** [comment]
Also interested in this

**Comment by cmer** [comment]
Interesting. I never knew this was an issue. I use my C2 with a Mac Mini (and previously Mac Studio). This hasn't been an issue.

If I understand correctly, the TV just forgets that you set the input as PC mode whenever you disconnect the HDMI cable from your MacBook?

**Comment by cmer** [comment]
It doesn't look like LGWebOSRemote supports changing the input mode, so we're out of luck on this front. I'm not sure if  it's even possible to change the input mode via the TV API.

I'll close this for now. If there's a way to make this work, I'd be down.

**Comment by cmer** [comment]
I just released a completely revamped version that automatically sets the input type to PC. Please reinstall and let me know if it works better for you!
