### ISSUE TITLE
Issues with Mac Mini M2 Pro and LG C4

### ISSUE THREAD

**Issue by ldzhjn** [cmer/lg-tv-control-macos#55]
I installed latest lg-tv-control-macos on my Mac Mini M2 Pro and found two issues.

1. When I try to manually put my Mac to sleep with keyboard shortcut Lock Screen (Control+Command+Q) then ESC, the first time TV is off without problem.
But after I wake the Mac up to the Lock Screen without login then press ESC to put my Mac to sleep again, the TV won't turn off.

From the debug log, there's no Received event: 3 from the second time when I put my Mac to sleep, looks like Hammerspoon can't intercept event: 3 from Lock Screen

2. After Mac sleeps for sometime, I can wake up the Mac using keyboard(I can confirm this because when I open the TV up the screen already shows Desktop), but the TV won't turn on.
From the debug log, it looks like this
2024-06-28 20:48:42: Received event: 4
2024-06-28 20:48:42: Received event: 0
2024-06-28 20:48:43: Received event: 11
Looks like Hammerspoon didn't trigger the command to turn on TV.

LG C4 firmware version 03.10.85
Using bluetooth keyboard and mouse with my Mac

**Comment by cmer** [comment]
Could you post the logs please?
