### ISSUE TITLE
Getting Timeout Message

### ISSUE THREAD

**Issue by GushersM** [cmer/lg-tv-control-macos#56]
Both the lgtv command installation, and when inputting a command, I get a timeout message as seen below. I've tried this multiple times, running the install.sh file, and the terminal code in the ReadMe multiple times. Not sure what is causing this, any help would be greatly appreciated

<img width="823" alt="Screenshot 2024-07-22 at 13 05 05" src="https://github.com/user-attachments/assets/07a3a080-27ff-45ee-9580-8384471d5c1f">

**Comment by cmer** [comment]
This seems to be a problem with the underlying library LGWebOSRemote and not this script. Try upgrading the library to see if it helps.
