### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by sslupsky** [cmer/lg-tv-control-macos#61]
I attempted to install and encountered the following error:
```
Homebrew is not installed. Please install Homebrew and try again.
```

Homebrew is installed and up to date:
```
stevenslupsky@barbie-en0 lg-tv-control-macos % brew --version
Homebrew 4.4.3
```

**Comment by sslupsky** [comment]
The problem is install.sh uses a non interactive shell which only parses .zshenv and does not parse .zprofile where the path to brew is set.  You might want to remove the first line of the install script.

**Comment by sslupsky** [comment]
Turns out there is another installation issue related to the ws4py dependency.  There are some python compatibility changes that are not included with the ws2py included with LGWebOSRemote.  This generates a couple syntax errors during the installation of ws4py.

https://github.com/klattimer/LGWebOSRemote/issues/172

**Comment by cmer** [comment]
I made a small tweak to `install.sh` which should handle the first issue you brought up. 

I just re-ran the installation script tonight for the first time in a while and also saw the errors you mention, but it does not appear to affect functionality. I'm hoping to switch away from LGWebOSRemote at one point, so fixing this isn't a big priority at the moment.
