### ISSUE TITLE
Interested in switching to Alga?

### ISSUE THREAD

**Issue by Tenzer** [cmer/lg-tv-control-macos#62]
Hi there. I have helped a bit with the maintenance of LGWebOSRemote but ended up writing my own alternative from scratch named [Alga](https://github.com/Tenzer/alga).

Among the reasons for making an alternative was to use a websocket library that is actively maintained, as ws4py which is used by LGWebOSRemote hasn't had a release since 2018.

I've noticed there's been a fair number of issues reported around LGWebOSRemote in relation to this project, and I wonder if they would have a better experience if it instead switched to using `alga`.

I am not a Hammerspoon user myself, so I might not be the best person to try it out. I've had a quick look through `lgtv_init.lua` and I think most commands have equivalent versions in `alga`.

Is this something you would be interested in trying out? I could perhaps make a PR with some rough changes so it can be tested out?

**Comment by cmer** [comment]
Yeah this is interesting! LGWebOSRemote hasn't been the easiest to work with.

I really wish there was a native binary we could use instead of having to rely on installing Python and other dependencies. Is this something you'd consider working on?

**Comment by cmer** [comment]
Awesome thank you! It'd make it easier for people to install my script. The hardest part for people is typically the Python stuff and dependencies.

**Comment by cmer** [comment]
Hey @Tenzer, have you been able to make any progress on this? Thanks!

**Comment by Tenzer** [comment]
Hi. I did start work on in, but I haven't found the time to complete it: https://github.com/Tenzer/alga/pull/65. I haven't forgotten about it though!

**Comment by cmer** [comment]
I just released a completely revamped version that uses bscpylgtv. I turned it into a portable executable. Therefore, I will not be switching to `alga`.
