### ISSUE TITLE
TV MAC acquisition appears to be malformed

### ISSUE THREAD

**Issue by tf5bassist** [cmer/lg-tv-control-macos#66]
Just installed the new version with the MAC gathering, and upon reloading the Hammerspoon config, received an error.

It seems that the MAC address that got populated into the lgtv.lua file is malformed:

```
local tv_ip = "192.168.0.111"
local tv_mac_address = "0:a1:59:67:xx:xx
0:a1:59:67:xx:xx"

```
The Terminal output shows this too:
```
Getting TV MAC address...
TV MAC Address: 0:a1:59:67:xx:xx
0:a1:59:67:xx:xx

```
It should be noted that it also failed to obtain both zeroes in the first octet.

Once I corrected the lua file to show the correct (singular) MAC, the script works.  I'll also test over a longer sleep period to see if it will be able to wake after the TV would previously disconnect the NIC.

**Comment by cmer** [comment]
Hmmm. Odd. What's output when you type `arp -n YOUR_TV_IP_HERE`?

**Comment by cmer** [comment]
Can you also try:

```
TV_IP=ip_goes_here
ping -c 1 $TV_IP > /dev/null 2>&1
arp -n $TV_IP | tail -n1 | awk '{print $4}' | awk '{print tolower($0)}'
```

And tell me if you get the correct output.

**Comment by cmer** [comment]
BTW I've updated the install script to be more resilient. It should solve this problem and prompt for a mac address if it can't be detected automatically.

**Comment by tf5bassist** [comment]
> arp -n YOUR_TV_IP_HERE

? (192.168.0.111) at 0:a1:59:67:xx:xx on en0 ifscope [ethernet]
? (192.168.0.111) at 0:a1:59:67:xx:xx on en7 ifscope [ethernet]

That's odd, I wonder if macOS is just like "Nah, no one needs leading zeroes" lmao

**Comment by tf5bassist** [comment]
> ```
> arp -n $TV_IP | tail -n1 | awk '{print $4}' | awk '{print tolower($0)}'
> ```

```
me@MacBook-Pro-2 lg-tv-control-macos % TV_IP=192.168.0.111
me@MacBook-Pro-2 lg-tv-control-macos % ping -c 1 $TV_IP > /dev/null 2>&1
me@MacBook-Pro-2 lg-tv-control-macos % arp -n $TV_IP | tail -n1 | awk '{print $4}' | awk '{print tolower($0)}'

0:a1:59:67:xx:xx

```

The output of this and the previous reply did output the overall correct MAC, just with a single digit first octet.
